
name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job 1"
  
  job2:
    runs-on: ubuntu-latest
    if: false
    needs: job1
    steps:
      - name: Step 2
        run: echo "This is job 2"
  
  job3:
    runs-on: ubuntu-latest
    if: ${{ needs.job1.result == 'success' && (needs.job2.result == 'success' || needs.job2.result == 'skipped') }}
    needs: [job1, job2]
    steps:
      - name: Step 3
        run: echo "This is job 3"
