
name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          exit 0
  
  job2:
    runs-on: ubuntu-latest
    if: true
    outputs:
      job3_should_run: ${{ steps.step2.outputs.job3_should_run }}
    needs: job1
    steps:
      - name: Step 2
        id: step2
        run: echo job3_should_run=true >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    if: ${{ needs.job2.outputs.job3_should_run == 'true' }}
    steps:
      - name: Step 3
        run: exit 0

  job4:
    runs-on: ubuntu-latest
    needs: [job2]
    if: ${{ needs.job2.outputs.job3_should_run == 'false' }}
    steps:
      - name: Step 3
        run: echo "This is job 3"

  job5:
    runs-on: ubuntu-latest
    if: |
      always() && 
      needs.job1.result == 'success' && 
      (needs.job2.result == 'success' || needs.job2.result == 'skipped') &&
      (needs.job3.result == 'success' || needs.job4.result == 'success')
    needs: [job1, job2, job3, job4]
    steps:
      - name: Step 3
        run: echo "This is job 3"
