
name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          exit 0
  
  job2:
    runs-on: ubuntu-latest
    if: true
    needs: job1
    steps:
      - name: Step 2
        run: exit 1
  
  job3:
    runs-on: ubuntu-latest
    if: |
      always() && 
      needs.job1.result == 'success' && 
      (needs.job2.result == 'success' || needs.job2.result == 'skipped')
    needs: [job1, job2]
    steps:
      - name: Step 3
        run: echo "This is job 3"
